#!/bin/bash

# panel install
cd /home/ptero/
php artisan down
curl -L https://github.com/Nookure/NookTheme/releases/latest/download/panel.tar.gz | tar -xzv
chmod -R 755 storage/* bootstrap/cache
composer install --no-dev --optimize-autoloader
php artisan view:clear
php artisan config:clear
php artisan migrate --seed --force
chown -R www-data:www-data /home/ptero/*
php artisan queue:restart
php artisan up

# done
clear
echo 'made by Darsh'
